### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by yl070360**
add LICENSE

### CODE REVIEW

**Comment by yl070360** [comment]
Hi，I like your source very much in my development，Thanks a lot. 
I wish to get your permission，Would you like to add an LICENSE?
Best wishes！

**Comment by vovayatsyuk** [comment]
Thank you! Please replace your name "yl070360" with "Swissup" in the license text.

**Comment by vovayatsyuk** [comment]
Thank you!

**Comment by yl070360** [comment]
I am very sorry for the mistake（github generate the license automatically），
I fix it，very sorry and appreciate!
Best Wishes!
















At 2022-05-27 15:11:38, "Vova Yatsyuk" ***@***.***> wrote:

Thank you! Please replace your name "yl070360" with "Swissup" in the license text.

**Pull request merged**
